*********************************************************************
* Sistema     : Gest∆o de Financiamentos
* Copyright   : Airam Miranda de Almeida
* Programador : Airam Miranda de Almeida
*********************************************************************
* Programa    : PASS.PRG
* Data        : 01/01/99
* Objetivo    : ---
* PRG"s       : ---
* DBF"s       : ---
* Alteracao   :
************************* inicio ************************************
                
PIC[1] ="@R 99999999"
PIC[2] ="@S50"
PIC[3] ="@S14"
PIC[4] ="@S12"
PIC[5] ="@S2"
PIC[6] ="  /  /  "
PIC[7] ="@S10"
PIC[8] ="@S1"
PIC[9] ="  /  /  "
PIC[10]="@S50"
PIC[11]="@S20"
PIC[12]="@S20"
PIC[13]="@S2"
PIC[14]="@R XXXXX-XXX"
PIC[15]="@R (9999) 999-9999"
PIC[16]="@R (9999) 999-9999"
PIC[17]="@S80"
PIC[18]="@S80"
PIC[19]="@S80"
PIC[20]="@S1"
