*********************************************************************
* Sistema     : Gest‹¨«o de Financiamentos                        
* Copyright   : Airam Miranda de Almeida
* Programador : Airam Miranda de Almeida
*********************************************************************
* Programa    : VELHO.PRG
* Data        : 01/01/99
* Objetivo    : ---
* PRG"s       : ---
* DBF"s       : ---
* Alteracao   :
************************* inicio ************************************
function VELHO()
DO CASE
 CASE ePERIODO = "T"
  IF eORIGEM = "A"
     DO CASE
     CASE ePROTESTO = "A"
      SET FILTER TO (DATA_VENC >= eDATA_INI .AND. DATA_VENC <= eDATA_FIM .AND. VLR_PGTO <> 0) .AND. ATIVA .AND. CONTABIL .AND. (DATA_PGTO >= eDATA_INI .AND. DATA_PGTO <= eDATA_FIM)
     CASE ePROTESTO = "P"
      SET FILTER TO (DATA_VENC >= eDATA_INI .AND. DATA_VENC <= eDATA_FIM .AND. VLR_PGTO <> 0) .AND. ATIVA .AND. CONTABIL .AND. PROTESTO .AND. (DATA_PGTO >= eDATA_INI .AND. DATA_PGTO <= eDATA_FIM)
     CASE ePROTESTO = "N"
      SET FILTER TO (DATA_VENC >= eDATA_INI .AND. DATA_VENC <= eDATA_FIM .AND. VLR_PGTO <> 0) .AND. ATIVA .AND. CONTABIL .AND. .NOT. PROTESTO .AND. (DATA_PGTO >= eDATA_INI .AND. DATA_PGTO <= eDATA_FIM)
     ENDCASE
   ELSE 
     IF eORIGEM = "C"
      DO CASE
      CASE ePROTESTO = "A"
       SET FILTER TO (DATA_VENC >= eDATA_INI .AND. DATA_VENC <= eDATA_FIM .AND. VLR_PGTO <> 0) .AND. ATIVA .AND. CONTABIL .AND. ORIGEM = "B" .AND. (DATA_PGTO >= eDATA_INI .AND. DATA_PGTO <= eDATA_FIM)
      CASE ePROTESTO = "P"
       SET FILTER TO (DATA_VENC >= eDATA_INI .AND. DATA_VENC <= eDATA_FIM .AND. VLR_PGTO <> 0) .AND. ATIVA .AND. CONTABIL .AND. ORIGEM = "B" .AND. PROTESTO .AND. (DATA_PGTO >= eDATA_INI .AND. DATA_PGTO <= eDATA_FIM)
      CASE ePROTESTO = "N"
       SET FILTER TO (DATA_VENC >= eDATA_INI .AND. DATA_VENC <= eDATA_FIM .AND. VLR_PGTO <> 0) .AND. ATIVA .AND. CONTABIL .AND. ORIGEM = "B" .AND. .NOT. PROTESTO .AND. (DATA_PGTO >= eDATA_INI .AND. DATA_PGTO <= eDATA_FIM)
      ENDCASE
     ELSE
      DO CASE
      CASE ePROTESTO = "A"
       SET FILTER TO (DATA_VENC >= eDATA_INI .AND. DATA_VENC <= eDATA_FIM .AND. VLR_PGTO <> 0) .AND. ATIVA .AND. CONTABIL .AND. ORIGEM = " " .AND. (DATA_PGTO >= eDATA_INI .AND. DATA_PGTO <= eDATA_FIM)
      CASE ePROTESTO = "P"
       SET FILTER TO (DATA_VENC >= eDATA_INI .AND. DATA_VENC <= eDATA_FIM .AND. VLR_PGTO <> 0) .AND. ATIVA .AND. CONTABIL .AND. ORIGEM = " " .AND. PROTESTO .AND. (DATA_PGTO >= eDATA_INI .AND. DATA_PGTO <= eDATA_FIM)
      CASE ePROTESTO = "N"
       SET FILTER TO (DATA_VENC >= eDATA_INI .AND. DATA_VENC <= eDATA_FIM .AND. VLR_PGTO <> 0) .AND. ATIVA .AND. CONTABIL .AND. ORIGEM = " " .AND. .NOT. PROTESTO .AND. (DATA_PGTO >= eDATA_INI .AND. DATA_PGTO <= eDATA_FIM)
      ENDCASE
     ENDIF
    ENDIF
 CASE ePERIODO = "A"
   IF eORIGEM = "A"
    DO CASE
    CASE ePROTESTO = "A"
     SET FILTER TO (DATA_VENC >= eDATA_INI .AND. DATA_VENC <= eDATA_FIM .AND. VLR_PGTO <> 0) .AND. ATIVA .AND. CONTABIL .AND. (DATA_PGTO >= eDATA_INI .AND. DATA_PGTO <= eDATA_FIM) .AND. (DATA_VENC < DATA_INI)
    CASE ePROTESTO = "P"
     SET FILTER TO (DATA_VENC >= eDATA_INI .AND. DATA_VENC <= eDATA_FIM .AND. VLR_PGTO <> 0) .AND. ATIVA .AND. CONTABIL .AND. PROTESTO .AND. (DATA_PGTO >= eDATA_INI .AND. DATA_PGTO <= eDATA_FIM) .AND. (DATA_VENC < DATA_INI)
    CASE ePROTESTO = "N"
     SET FILTER TO (DATA_VENC >= eDATA_INI .AND. DATA_VENC <= eDATA_FIM .AND. VLR_PGTO <> 0) .AND. ATIVA .AND. CONTABIL .AND. .NOT. PROTESTO .AND. (DATA_PGTO >= eDATA_INI .AND. DATA_PGTO <= eDATA_FIM) .AND. (DATA_VENC < DATA_INI)
    ENDCASE
   ELSE 
    IF eORIGEM = "C"
     DO CASE
     CASE ePROTESTO = "A"
      SET FILTER TO (DATA_VENC >= eDATA_INI .AND. DATA_VENC <= eDATA_FIM .AND. VLR_PGTO <> 0) .AND. ATIVA .AND. CONTABIL .AND. ORIGEM = "B" .AND. (DATA_PGTO >= eDATA_INI .AND. DATA_PGTO <= eDATA_FIM) .AND. (DATA_VENC < DATA_INI)
     CASE ePROTESTO = "P"
      SET FILTER TO (DATA_VENC >= eDATA_INI .AND. DATA_VENC <= eDATA_FIM .AND. VLR_PGTO <> 0) .AND. ATIVA .AND. CONTABIL .AND. ORIGEM = "B" .AND. PROTESTO .AND. (DATA_PGTO >= eDATA_INI .AND. DATA_PGTO <= eDATA_FIM) .AND. (DATA_VENC < DATA_INI)
     CASE ePROTESTO = "N"
      SET FILTER TO (DATA_VENC >= eDATA_INI .AND. DATA_VENC <= eDATA_FIM .AND. VLR_PGTO <> 0) .AND. ATIVA .AND. CONTABIL .AND. ORIGEM = "B" .AND. .NOT. PROTESTO .AND. (DATA_PGTO >= eDATA_INI .AND. DATA_PGTO <= eDATA_FIM) .AND. (DATA_VENC < DATA_INI)
     ENDCASE
    ELSE
     DO CASE
     CASE ePROTESTO = "A"
      SET FILTER TO (DATA_VENC >= eDATA_INI .AND. DATA_VENC <= eDATA_FIM .AND. VLR_PGTO <> 0) .AND. ATIVA .AND. CONTABIL .AND. ORIGEM = " " .AND. (DATA_PGTO >= eDATA_INI .AND. DATA_PGTO <= eDATA_FIM) .AND. (DATA_VENC < DATA_INI)
     CASE ePROTESTO = "P"
      SET FILTER TO (DATA_VENC >= eDATA_INI .AND. DATA_VENC <= eDATA_FIM .AND. VLR_PGTO <> 0) .AND. ATIVA .AND. CONTABIL .AND. ORIGEM = " " .AND. PROTESTO .AND. (DATA_PGTO >= eDATA_INI .AND. DATA_PGTO <= eDATA_FIM) .AND. (DATA_VENC < DATA_INI)
     CASE ePROTESTO = "N"
      SET FILTER TO (DATA_VENC >= eDATA_INI .AND. DATA_VENC <= eDATA_FIM .AND. VLR_PGTO <> 0) .AND. ATIVA .AND. CONTABIL .AND. ORIGEM = " " .AND. .NOT. PROTESTO .AND. (DATA_PGTO >= eDATA_INI .AND. DATA_PGTO <= eDATA_FIM) .AND. (DATA_VENC < DATA_INI)
     ENDCASE
    ENDIF
   ENDIF
 CASE ePERIODO = "P"
   IF eORIGEM = "A"
    DO CASE
    CASE ePROTESTO = "A"
     SET FILTER TO (DATA_VENC >= eDATA_INI .AND. DATA_VENC <= eDATA_FIM .AND. VLR_PGTO <> 0) .AND. ATIVA .AND. CONTABIL .AND. (DATA_PGTO >= eDATA_INI .AND. DATA_PGTO <= eDATA_FIM) .AND. DATA_VENC > eDATA_FIM
    CASE ePROTESTO = "P"
     SET FILTER TO (DATA_VENC >= eDATA_INI .AND. DATA_VENC <= eDATA_FIM .AND. VLR_PGTO <> 0) .AND. ATIVA .AND. CONTABIL .AND. PROTESTO .AND. (DATA_PGTO >= eDATA_INI .AND. DATA_PGTO <= eDATA_FIM) .AND. DATA_VENC > eDATA_FIM
    CASE ePROTESTO = "N"
     SET FILTER TO (DATA_VENC >= eDATA_INI .AND. DATA_VENC <= eDATA_FIM .AND. VLR_PGTO <> 0) .AND. ATIVA .AND. CONTABIL .AND. .NOT. PROTESTO .AND. (DATA_PGTO >= eDATA_INI .AND. DATA_PGTO <= eDATA_FIM) .AND. DATA_VENC > eDATA_FIM
    ENDCASE
   ELSE 
    IF eORIGEM = "C"
     DO CASE
     CASE ePROTESTO = "A"
      SET FILTER TO (DATA_VENC >= eDATA_INI .AND. DATA_VENC <= eDATA_FIM .AND. VLR_PGTO <> 0) .AND. ATIVA .AND. CONTABIL .AND. ORIGEM = "B" .AND. (DATA_PGTO >= eDATA_INI .AND. DATA_PGTO <= eDATA_FIM) .AND. DATA_VENC > eDATA_FIM
     CASE ePROTESTO = "P"
      SET FILTER TO (DATA_VENC >= eDATA_INI .AND. DATA_VENC <= eDATA_FIM .AND. VLR_PGTO <> 0) .AND. ATIVA .AND. CONTABIL .AND. ORIGEM = "B" .AND. PROTESTO .AND. (DATA_PGTO >= eDATA_INI .AND. DATA_PGTO <= eDATA_FIM) .AND. DATA_VENC > eDATA_FIM
     CASE ePROTESTO = "N"
      SET FILTER TO (DATA_VENC >= eDATA_INI .AND. DATA_VENC <= eDATA_FIM .AND. VLR_PGTO <> 0) .AND. ATIVA .AND. CONTABIL .AND. ORIGEM = "B" .AND. .NOT. PROTESTO .AND. (DATA_PGTO >= eDATA_INI .AND. DATA_PGTO <= eDATA_FIM) .AND. DATA_VENC > eDATA_FIM
     ENDCASE
    ELSE
     DO CASE
     CASE ePROTESTO = "A"
      SET FILTER TO (DATA_VENC >= eDATA_INI .AND. DATA_VENC <= eDATA_FIM .AND. VLR_PGTO <> 0) .AND. ATIVA .AND. CONTABIL .AND. ORIGEM = " " .AND. (DATA_PGTO >= eDATA_INI .AND. DATA_PGTO <= eDATA_FIM) .AND. DATA_VENC > eDATA_FIM
     CASE ePROTESTO = "P"
      SET FILTER TO (DATA_VENC >= eDATA_INI .AND. DATA_VENC <= eDATA_FIM .AND. VLR_PGTO <> 0) .AND. ATIVA .AND. CONTABIL .AND. ORIGEM = " " .AND. PROTESTO .AND. (DATA_PGTO >= eDATA_INI .AND. DATA_PGTO <= eDATA_FIM) .AND. DATA_VENC > eDATA_FIM
     CASE ePROTESTO = "N"
      SET FILTER TO (DATA_VENC >= eDATA_INI .AND. DATA_VENC <= eDATA_FIM .AND. VLR_PGTO <> 0) .AND. ATIVA .AND. CONTABIL .AND. ORIGEM = " " .AND. .NOT. PROTESTO .AND. (DATA_PGTO >= eDATA_INI .AND. DATA_PGTO <= eDATA_FIM) .AND. DATA_VENC > eDATA_FIM
     ENDCASE
    ENDIF
   ENDIF
 CASE ePERIODO = "M"
   IF eORIGEM = "A"
    DO CASE
    CASE ePROTESTO = "A"
     SET FILTER TO (DATA_VENC >= eDATA_INI .AND. DATA_VENC <= eDATA_FIM .AND. VLR_PGTO <> 0) .AND. ATIVA .AND. CONTABIL .AND. (DATA_PGTO >= eDATA_INI .AND. DATA_PGTO <= eDATA_FIM)  
    CASE ePROTESTO = "P"
     SET FILTER TO (DATA_VENC >= eDATA_INI .AND. DATA_VENC <= eDATA_FIM .AND. VLR_PGTO <> 0) .AND. ATIVA .AND. CONTABIL .AND. PROTESTO .AND. (DATA_PGTO >= eDATA_INI .AND. DATA_PGTO <= eDATA_FIM)  
    CASE ePROTESTO = "N"
     SET FILTER TO (DATA_VENC >= eDATA_INI .AND. DATA_VENC <= eDATA_FIM .AND. VLR_PGTO <> 0) .AND. ATIVA .AND. CONTABIL .AND. .NOT. PROTESTO .AND. (DATA_PGTO >= eDATA_INI .AND. DATA_PGTO <= eDATA_FIM)  
    ENDCASE
   ELSE 
    IF eORIGEM = "C"
     DO CASE
     CASE ePROTESTO = "A"
      SET FILTER TO (DATA_VENC >= eDATA_INI .AND. DATA_VENC <= eDATA_FIM .AND. VLR_PGTO <> 0) .AND. ATIVA .AND. CONTABIL .AND. ORIGEM = "B" .AND. (DATA_PGTO >= eDATA_INI .AND. DATA_PGTO <= eDATA_FIM)
     CASE ePROTESTO = "P"
      SET FILTER TO (DATA_VENC >= eDATA_INI .AND. DATA_VENC <= eDATA_FIM .AND. VLR_PGTO <> 0) .AND. ATIVA .AND. CONTABIL .AND. ORIGEM = "B" .AND. PROTESTO .AND. (DATA_PGTO >= eDATA_INI .AND. DATA_PGTO <= eDATA_FIM) 
     CASE ePROTESTO = "N"
      SET FILTER TO (DATA_VENC >= eDATA_INI .AND. DATA_VENC <= eDATA_FIM .AND. VLR_PGTO <> 0) .AND. ATIVA .AND. CONTABIL .AND. ORIGEM = "B" .AND. .NOT. PROTESTO .AND. (DATA_PGTO >= eDATA_INI .AND. DATA_PGTO <= eDATA_FIM) 
     ENDCASE
    ELSE
     DO CASE
     CASE ePROTESTO = "A"
      SET FILTER TO (DATA_VENC >= eDATA_INI .AND. DATA_VENC <= eDATA_FIM .AND. VLR_PGTO <> 0) .AND. ATIVA .AND. CONTABIL .AND. ORIGEM = " " .AND. (DATA_PGTO >= eDATA_INI .AND. DATA_PGTO <= eDATA_FIM) 
     CASE ePROTESTO = "P"
      SET FILTER TO (DATA_VENC >= eDATA_INI .AND. DATA_VENC <= eDATA_FIM .AND. VLR_PGTO <> 0) .AND. ATIVA .AND. CONTABIL .AND. ORIGEM = " " .AND. PROTESTO .AND. (DATA_PGTO >= eDATA_INI .AND. DATA_PGTO <= eDATA_FIM)
     CASE ePROTESTO = "N"
      SET FILTER TO (DATA_VENC >= eDATA_INI .AND. DATA_VENC <= eDATA_FIM .AND. VLR_PGTO <> 0) .AND. ATIVA .AND. CONTABIL .AND. ORIGEM = " " .AND. .NOT. PROTESTO .AND. (DATA_PGTO >= eDATA_INI .AND. DATA_PGTO <= eDATA_FIM)
     ENDCASE
    ENDIF
   ENDIF
ENDCASE
RETURN NIL
